
name:BJUT_Clock_In

on:
  push:
  schedule:
    # 定时任务，在每天上午5点10分进行打卡
    - cron: '10 21 * * *'

jobs:
  clock:
    runs-on: ubuntu-latest
    steps:

      # 首先copy git仓库到虚拟机上
      - name: 'Checkout codes'
        uses: actions/checkout@v1

      # 执行仓库中的脚本文件
      - name: 'Clock In'
        run: python3 ./././bjut1.py
        env:
          EMAIL_USERNAME: ${{secrets.EMAIL_USERNAME}}
          EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}}

          EMAIL_RECEIVER_1: ${{secrets.EMAIL_RECEIVER_1}}
          EMAIL_RECEIVER_2: ${{secrets.EMAIL_RECEIVER_2}}
          EMAIL_RECEIVER_3: ${{secrets.EMAIL_RECEIVER_3}}
          EMAIL_RECEIVER_4: ${{secrets.EMAIL_RECEIVER_4}}
          EMAIL_RECEIVER_5: ${{secrets.EMAIL_RECEIVER_5}}

          ID_1: ${{secrets.ID_1}}
          ID_2: ${{secrets.ID_2}}
          ID_3: ${{secrets.ID_3}}
          ID_4: ${{secrets.ID_4}}
          ID_5: ${{secrets.ID_5}}

          TOKEN_1: ${{secrets.TOKEN_1}}
          TOKEN_2: ${{secrets.TOKEN_2}}
          TOKEN_3: ${{secrets.TOKEN_3}}
          TOKEN_4: ${{secrets.TOKEN_4}}
          TOKEN_5: ${{secrets.TOKEN_5}}

